[package]
name = "pom"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10.0", features = ["async-std"] }
rusql-alchemy = "0.3.0"
sqlx = "0.8.0"
tokio = { version = "1.40.0", features = ["tokio-macros", "rt-multi-thread"] }
